name: SonarCloud Frontend
on:
  push:
  pull_request:
jobs:
  frontend:
    name: Build and analyze Frontend code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: front
        run: npm install

      - name: Sonar Scan Frontend
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY_FRONTEND }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_V2 }}
