name: GitHub Actions test coverage
on:
  pull_request:
  push:
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build and test back
        working-directory: back
        run: |
          mvn clean test
          mvn jacoco:report
      - name: Upload backend coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: back/target/site/jacoco
      - run: echo "This job's status is ${{ job.status }}."
  frontend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
        working-directory: front
      - name: Run tests with coverage
        run: npm test -- --code-coverage
        working-directory: front
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: front/coverage
      - run: echo "This job's status is ${{ job.status }}."
      