name: GitHub Actions test coverage
on:
  pull_request:
  push:
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: mvn clean test
      - run: mvn jacoco:report
      - run: echo "This job's status is ${{ job.status }}."